apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio-development

resources:
  - ../../base

images:
  - name: quay.io/moabdelbasset/portolio-flask
    digest: sha256:85e7a1936b2a3d90cb2b681f0cfa916d9e47458509b7705d92ba6b9a70bf0f26

patches:
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: portfolio
    patch: |-
      - op: add
        path: /spec/host
        value: portfolio-development.apps.ocp-lab.aymantech.net